<?php

return array (
  'name' => 'Web',
  'fixedpage' => 'general/config',
  'configgroup' => 
  array (
    'site' => '站点配置',
    'company_profile' => '公司简介',
    'contact_us' => '联系我们',
    'wechat' => '小程序设置',
    'basic' => '基础配置',
    'dictionary' => '系统栏目配置',
  ),
  'appid' => 'AppID',
  'secret' => 'AppSecret',
  'version' => '1.0.1',
  'contact_person' => '顾先生',
  'phone1' => '151-0825-9704',
  'phone2' => '151-0825-9704',
  'email' => 'sc_yohope@outlook.com',
  'address' => '四川省成都市',
  'case_number' => '蜀ICP备2020035041号',
  'company_name' => '四川省远鸿项目管理有限公司',
  'company_profile' => '<p><span style="font-size: 1.25em;"><b>四川省远鸿项目管理有限公司</b></span><span style="font-size: 1.25em;">成立于2020年8月30日，本公司主要开展以工程设计、工程监理、工程施工、工程造价、施工许可证、竣工验收、消防验收、消防开检、各类资质的相关业务代理手续为主的业务，营业经营范围包含：注项目管理；工程造价咨询；招投标代理；工程监理；工程技术咨询服务；信息技术咨询服务；建筑劳务分包；人力资源中介服务；企业管理；销售；建材。</span></p><p><span style="font-size: 1.25em;"><br></span></p><p><span style="font-size: 1.25em;">我们的理念:“</span><span style="font-size: large;"><b style="">诚信为本、实力为先，全心全意为客户</b>”</span><span style="font-size: 1.25em;">。我们公司秉承客户至上、服务至上的经营理念，以卓越的服务品质、专业的技术服务实力的客户服务团队，保障客户在建设的高速路上驰骋，又以稳固、发展、忠诚、高效、团结与创新的精神，尊重人才、注重技术，使客户在享受优质服务的同时不断获得最大的收益。</span></p>',
  'introduce_title' => '远鸿管理',
  'introduce_content' => '<p><span style="font-size: 1.25em;">远鸿管理总部坐落于美丽的天府之国——成都。远鸿管理坚持“细致周到，效率至上”的服务理念，以客户为中心，结合自身先进业务技术，旨在为企业、商家扫清开业过程中的一切障碍。</span><br></p><p><span style="font-size: 1.25em;"><br></span></p><p>公司深耕行业多年，聚集领域人才，在多地区业务处理中拥有丰富经验。创建以来，公司为迎合市场需求，响应政府号召，建立了创新的管理模式和业务流程。未来，公司将在业务流程智能化做更多探索，为客户提供更高效智能的服务。</p>',
  'introduce_text1' => '业务种类',
  'introduce_text2' => '服务市县',
  'introduce_text3' => '商家合作',
  'introduce_num1' => '20',
  'introduce_num2' => '20',
  'introduce_num3' => '100',
  'image' => '/uploads/20201223/a1b6ec9f931f516420d8d570f371e6de.png',
  'contact_title' => '四川省成都市远鸿项目管理有限公司',
  'contact_address' => '四川省成都市',
  'contact_web_url' => 'http://www.yohope.ltd/',
  'contact_phone' => '151-0825-9704',
  'contact_email' => 'sc_yohope@outlook.com',
  'qr_code' => '/uploads/20201224/264d455422d646e69c8f4e634e56577e.jpg',
);